apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platforms-service
  template:
    metadata:
      labels:
        app: platforms-service
    spec:
      containers:
        - name: platforms-service
          image: eyndrahena/platforms-service:latest

---

apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platforms-service
  ports:
    - name: platforms-service
      protocol: TCP
      port: 80
      targetPort: 80
    - name: platforms-grpc
      protocol: TCP
      port: 666
      targetPort: 666

# kubectl apply -f .\platforms-depl.yaml
