apiVersion: v1
kind: Service
metadata:
  name: platforms-np-service-srv
spec:
  type: NodePort
  selector:
    app: platforms-service
  ports:
    - name: platforms-service
      protocol: TCP
      port: 80
      targetPort: 80

# kubectl apply -f .\platforms-np-srv.yaml
